"""Question wordings per boolean field, four each. Index 3 is used only in the frozen holdout.

Written by Claude, not by a native annotator: have a Finnish speaker read them before the
set is used to judge a model.
"""
QUESTIONS={
'policyInForce':['Oliko vakuutus voimassa vahinkohetkellä?','Oliko vakuutusturva voimassa vahingon sattuessa?','Onko vakuutus ollut voimassa vahinkopäivänä?','Oliko ajoneuvon vakuutus voimassa silloin, kun vahinko tapahtui?'],
'isTransportNegligence':['Johtuiko vahinko kuljetuksen aikaisesta huolimattomuudesta?','Aiheutuiko vahinko huolimattomuudesta ajoneuvoa kuljetettaessa?','Oliko vahingon syynä huolimattomuus kuljetuksen aikana?','Sattuiko vahinko siksi, että ajoneuvon kuljetuksessa oltiin huolimattomia?'],
'isLicenseOrSkillCourseTraining':['Tapahtuiko vahinko ajokortti- tai ajotaitokurssilla?','Oliko vahinkohetkellä kyse ajokorttikoulutuksesta tai ajotaitokurssista?','Ajettiinko ajoneuvoa vahinkohetkellä ajokortti- tai ajotaitokoulutuksessa?','Sattuiko vahinko ajo-opetuksen tai ajotaitokurssin aikana?'],
'damageInNordicArea':['Sattuiko vahinko Pohjoismaissa?','Tapahtuiko vahinko jossakin Pohjoismaassa?','Oliko vahinkopaikka Pohjoismaiden alueella?','Onko vahinko sattunut Pohjoismaiden alueella?'],
'myyntiOlisiOllutAlvVelvollinen':['Olisiko ajoneuvon myynti ollut arvonlisäverovelvollista?','Olisiko ajoneuvon myynnistä pitänyt maksaa arvonlisävero?','Olisiko ajoneuvon myyntiin liittynyt arvonlisäverovelvollisuus?','Olisiko myyntitilanteessa sovellettu arvonlisäveroa ajoneuvon hintaan?'],
'isDirectConsequenceOfCoveredEvent':['Oliko vahinko välitön seuraus korvattavasta tapahtumasta?','Johtuiko vahinko suoraan korvattavasta tapahtumasta?','Aiheutuiko vahinko välittömästi korvattavan tapahtuman seurauksena?','Oliko vahingon välitön syy korvattava tapahtuma?'],
'isLoadingOrUnloadingDamage':['Syntyikö vahinko lastauksen tai purkamisen yhteydessä?','Tapahtuiko vahinko ajoneuvoa lastattaessa tai purettaessa?','Oliko kyse lastaus- tai purkutilanteessa syntyneestä vahingosta?','Sattuiko vahinko lastauksen tai purun aikana?'],
'powertrainDamagedByInsufficientOilOrCoolantCirculation':['Vaurioituiko voimansiirto riittämättömän öljyn tai jäähdytysnesteen kierron takia?','Johtuiko voimansiirron vaurio siitä, että öljy tai jäähdytysneste ei kiertänyt riittävästi?','Aiheutuiko voimansiirron vaurio puutteellisesta öljyn tai jäähdytysnesteen kierrosta?','Oliko voimansiirron vaurion syynä liian vähäinen öljyn tai jäähdytysnesteen kierto?'],
'partOrEquipmentDamagedByDefectWearOrDeficientMaintenance':['Johtuiko osan tai laitteen vaurio viasta, kulumisesta tai puutteellisesta huollosta?','Vaurioituiko osa tai laite vian, kulumisen tai huollon laiminlyönnin vuoksi?','Aiheutuiko osan tai laitteen vaurio viasta, kulumisesta tai puutteellisesta kunnossapidosta?','Oliko osan tai laitteen vaurion syy vika, kuluminen tai huoltamattomuus?'],
'damageCausedByDrivingOnWaterCoveredRoadOrArea':['Aiheutuiko vahinko ajamisesta veden peittämällä tiellä tai alueella?','Tapahtuiko vahinko ajettaessa veden peittämällä tiellä tai alueella?','Ajettiinko vahinkohetkellä veden peittämälle tielle tai alueelle?','Johtuiko vahinko siitä, että ajoneuvolla ajettiin veden peittämällä alueella?'],
'waterSnowOrHailEnteredInteriorThroughOpenOpening':['Pääsikö vettä, lunta tai rakeita sisätiloihin avoimen aukon kautta?','Tunkeutuiko vesi, lumi tai rae ajoneuvon sisään avoimesta aukosta?','Oliko vettä, lunta tai rakeita päässyt sisätiloihin avoimen ikkunan tai luukun kautta?','Kulkeutuiko vesi, lumi tai rae sisätiloihin avoinna olleen aukon kautta?'],
'carelessServiceOrHandling':['Johtuiko vahinko huolimattomasta huollosta tai käsittelystä?','Aiheutuiko vahinko huolimattomasta huoltotyöstä tai käsittelystä?','Oliko vahingon syynä huolimaton huolto tai käsittely?','Syntyikö vahinko siitä, että ajoneuvoa huollettiin tai käsiteltiin huolimattomasti?'],
'nonExemptVehicleSankThroughIceOutsideApprovedWinterRoad':['Vajosiko ajoneuvo jään läpi hyväksytyn talvitien ulkopuolella?','Putosiko ajoneuvo jään läpi muualla kuin hyväksytyllä talvitiellä?','Upposiko ajoneuvo jäihin hyväksytyn talvitien ulkopuolella?','Oliko kyse ajoneuvosta, joka vajosi jään läpi muulla kuin hyväksytyllä talvitiellä?'],
'damageCausedByVehicleOrCombinationLoad':['Aiheutuiko vahinko ajoneuvon tai yhdistelmän kuormasta?','Johtuiko vahinko ajoneuvon tai ajoneuvoyhdistelmän kuljettamasta kuormasta?','Oliko vahingon aiheuttaja ajoneuvon tai yhdistelmän kuorma?','Syntyikö vahinko kuorman vuoksi?'],
'damageCausedByAnimalInVehicle':['Aiheuttiko ajoneuvossa ollut eläin vahingon?','Johtuiko vahinko ajoneuvon sisällä olleesta eläimestä?','Oliko vahingon aiheuttajana ajoneuvossa matkustanut eläin?','Syntyikö vahinko siitä, että ajoneuvossa oli eläin?'],
'vehicleDamagedByItsOwnPartOrDevice':['Vaurioittiko ajoneuvon oma osa tai laite ajoneuvoa?','Aiheutuiko vahinko ajoneuvon omasta osasta tai laitteesta?','Johtuiko vahinko siitä, että ajoneuvon oma osa tai laite vaurioitti ajoneuvoa?','Oliko vahingon aiheuttaja ajoneuvon oma osa tai laite?'],
'competitionPracticeOrTrackUse':['Oliko ajoneuvo kilpailu-, harjoitus- tai ratakäytössä?','Käytettiinkö ajoneuvoa kilpailussa, harjoituksessa tai radalla vahinkohetkellä?','Sattuiko vahinko kilpailun, harjoituksen tai ratakäytön aikana?','Oliko ajoneuvo vahinkohetkellä ratakäytössä, kilpailussa tai harjoittelussa?'],
'damageOccurredDuringAfterOrBecauseOfListedIntentionalActOrCrime':['Tapahtuiko vahinko tahallisen teon tai rikoksen aikana, jälkeen tai sen vuoksi?','Liittyikö vahinko tahalliseen tekoon tai rikokseen?','Sattuiko vahinko tahallisen teon tai rikoksen yhteydessä?','Oliko vahingon taustalla tahallinen teko tai rikos?'],
'nuclearDamagePresent':['Onko kyseessä ydinvahinko?','Johtuiko vahinko ydinenergiasta tai ydinaineista?','Onko vahinko aiheutunut ydinvahingosta?','Oliko vahinko ydinvahinko?'],
'damageCausedByListedCyberEvent':['Aiheutuiko vahinko kyberhyökkäyksestä?','Johtuiko vahinko kyberiskusta?','Oliko vahingon syynä kyberhyökkäys?','Syntyikö vahinko tietoverkkoon kohdistuneen hyökkäyksen seurauksena?'],
'singleDamageItemScopeConfirmed':['Onko vahinko vahvistettu yhdeksi vahinkokohteeksi?','Onko vahinkokohde vahvistettu yhdeksi kohteeksi?','Vahvistettiinko, että kyse on yhdestä vahinkokohteesta?','Onko varmistettu, että vahinko koskee vain yhtä kohdetta?'],
'ajoneuvoVajosiSuohon':['Vajosiko ajoneuvo suohon?','Upposiko ajoneuvo suohon?','Ajautuiko ajoneuvo suohon niin, että se vajosi?','Vajosiko ajoneuvo suomaastossa?'],
'osumaYlapuoliseenEsteeseen':['Osuiko ajoneuvo yläpuoliseen esteeseen?','Törmäsikö ajoneuvo ylhäällä olleeseen esteeseen?','Osuiko ajoneuvo esteeseen, joka oli sen yläpuolella?','Oliko vahinko seurausta osumasta yläpuoliseen esteeseen?'],
'ylapuolisenEsteenKuljetuspoikkeus':['Oliko yläpuolisen esteen osumaan kuljetuspoikkeus?','Liittyikö yläpuoliseen esteeseen osumiseen kuljetuspoikkeus?','Oliko yläpuolisen esteen osuman taustalla kuljetuspoikkeus?','Koskiko yläpuolisen esteen osumaa kuljetuspoikkeus?'],
}
ANSWERS={'true':['Kyllä.','Kyllä, näin on.','Kyllä, se pitää paikkansa.'],
         'false':['Ei.','Ei, ei näin.','Ei, se ei pidä paikkaansa.'],
         'null':['Ei tiedossa.','En osaa sanoa.','Tietoa ei ole saatavilla.']}
WRAPPERS=['{q} Vastaus: {a}','Kysymys: {q}\nVastaus: {a}','{q} – {a}']
